[project]
name = "dbapp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10.11"
dependencies = [
    "dotenv>=0.9.9",
    "flask>=3.1.2",
    "prometheus-client>=0.23.1",
    "pymongo>=4.15.3",
    "waitress>=3.0.2",
]
