apiVersion: v1
kind: ServiceAccount
metadata:
  name: ml-service-account
  namespace: ml
  annotations:
    iam.gke.io/gcp-service-account: ml-serviceaccount@mlops-476802.iam.gserviceaccount.com


    
