# Use a lightweight Python base image
FROM python:3.10-slim

# Set the working directory
WORKDIR /app

# Copy requirements first (for Docker cache efficiency)
COPY requirements.txt .

# Install system dependencies and Python packages
RUN apt-get update && apt-get install -y gcc && rm -rf /var/lib/apt/lists/* \
    && pip install --no-cache-dir -r requirements.txt

# Copy the rest of your project files
COPY . .

ENV PYTHONUNBUFFERED=1

# Command to run the daemon
CMD ["python", "cronjob.py"]
