FROM python:3.10-slim

WORKDIR /app

RUN pip install --no-cache-dir mlflow psycopg2-binary boto3

EXPOSE 5000

# Command: start the MLflow tracking server using env vars
CMD ["sh", "-c", "mlflow server \
    --backend-store-uri ${MLFLOW_BACKEND_STORE_URI} \
    --default-artifact-root ${MLFLOW_ARTIFACT_ROOT} \
    --host 0.0.0.0 \
    --port 5000"]
